### ISSUE TITLE
Handling differences in cyclesheets.

### ISSUE THREAD

**Issue by baishali-ghosh** [VIT-OCW/CSE308#1]
There are subtle differences and new exercises in our cyclesheets. For example, activity 7 asks for multitiered menu and the current code does not render it in the expected manner. 
Do you want
1) To make forks of the existing and develop independently
OR
2) Make separate folders semester wise?
OR
3) Update the existing code?

**Comment by karthikb351** [comment]
It would make things too complicated and hard to maintain if it was made into seperate folders/branches don't you think? 
I'd vote to just update the existing code and cycle sheet if it is for just minor changes.

**Comment by aneesh-neelam** [comment]
Update the existing code. They should be the proper solutions anyway.

**Comment by baishali-ghosh** [comment]
Activity 7 was not enitrely correct. It has now been rectified via 301cb8e522ab7b7d1d469dfbe9b6aabe719c459e
